import os, shutil
from typing import List
from .paths import project_root, safe_name
from .utils import ensure_dir, write_file
from .agent import AgentEvent

def scaffold_fullstack(stack: str, project: str, events: List[AgentEvent]) -> None:
    root = project_root(project)
    if os.path.exists(root):
        shutil.rmtree(root)
    ensure_dir(root)

    write_file(
        os.path.join(root, "README.md"),
        f"# {project}\n\nGenerated by Boardwalk AI Autonomous Builder.\nGoal: {project}\n",
    )

    if stack == "react-node":
        _scaffold_react_node(root, project, events)
    elif stack == "react-fastapi":
        _scaffold_react_fastapi(root, project, events)
    elif stack == "svelte-worker":
        _scaffold_svelte_worker(root, project, events)
    elif stack == "next-node":
        _scaffold_next(root, project, events)
    elif stack == "vanilla-html":
        _scaffold_vanilla(root, project, events)
    else:
        events.append(AgentEvent(kind="error", message=f"Unknown stack '{stack}'"))

def _scaffold_react_node(root: str, project: str, events: List[AgentEvent]) -> None:
    backend_dir = os.path.join(root, "backend")
    frontend_dir = os.path.join(root, "frontend")
    ensure_dir(backend_dir)
    ensure_dir(frontend_dir)

    write_file(
        os.path.join(backend_dir, "package.json"),
        """{
  "name": "backend",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "dev": "node server.js",
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.19.0",
    "cors": "^2.8.5"
  }
}
""",
    )
    write_file(
        os.path.join(backend_dir, "server.js"),
        """const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", (req, res) => {
  res.json({ ok: true, service: "backend", stack: "react-node" });
});

// TODO: wire in auth, DB, AI routes, media, etc.

const port = process.env.PORT || 4000;
app.listen(port, () => {
  console.log("Backend listening on port", port);
});
""",
    )

    write_file(
        os.path.join(frontend_dir, "package.json"),
        """{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""",
    )
    ensure_dir(os.path.join(frontend_dir, "src"))
    write_file(
        os.path.join(frontend_dir, "index.html"),
        """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React Frontend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
    )
    write_file(
        os.path.join(frontend_dir, "src", "main.jsx"),
        """import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>Laundry Bubbles / Boardwalk App</h1>
      <p>Generated by Boardwalk AI Autonomous Builder.</p>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
""",
    )
    events.append(AgentEvent(kind="agent", message="Scaffolded React + Node full stack."))

# (You can keep the other stack helpers from your original main.py, moved here)
def _scaffold_react_fastapi(root, project, events): ...
def _scaffold_svelte_worker(root, project, events): ...
def _scaffold_next(root, project, events): ...
def _scaffold_vanilla(root, project, events): ...
